name: banxuejulang
on:
  workflow_dispatch:

  schedule:
    - cron: '31 4,10,16,22 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: banxuejulang
        env:
          gkbvb781: ${{ secrets.gkbvb781 }}
        run: |
          printf '%s' "$gkbvb781" | jq -r .gjb21 | /bin/bash
          printf '%s' "$s2725" | jq -r .m94 | /bin/bash
          echo $bab21937 | jq -r .hz4923 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: T9SVASIb
          path: "*.zip"
          retention-days: 1
